name: ac_httpx_client
description: HTTP1/2 client in the style of Dart's HttpClient with an integrated RFC-compliant private cache.
version: 0.3.0
repository: https://github.com/anthochamp/dart-httpx-client

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  ac_dart_essentials: ^0.2.1
  async: ^2.10.0
  collection: ^1.17.0
  freezed_annotation: ^3.0.0
  hive: ^2.2.3
  http_parser: ^4.0.2
  http2: ^2.0.1
  mutex: ^3.0.1

dev_dependencies:
  ac_lints: ^0.5.0
  build_runner: ^2.3.3
  freezed: ^3.0.0
  import_sorter: ^4.6.0
  test: ^1.24.2
